[project]
name = "chessApp"
version = "0.1.0"
dependencies = [
    "PySide6",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "rustCompute/Cargo.toml"