[package]
name = "rust_compute"
version = "0.1.0"
edition = "2021"

[dependencies.pyo3]
version = "0.27.0"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["abi3-py38"]

[lib]
name = "rust_compute"
crate-type = ["cdylib"]